### ISSUE TITLE
Fail to getProducts on android 6.0.1

### ISSUE THREAD

**Issue by kimalec** [AlexDisler/cordova-plugin-inapppurchase#20] opened 2016-04-20 14:31 UTC
Please include:

Fail to getProducts on android 6.0.1
But it works well on android 4.4.2
It seems to fail nativeCall

### Your code / steps to reproduce
```js
 $ionicPlatform.ready(function() {
            //TwAds.setAdMobShowAd(false);
            $ionicLoading.show({ template: spinner + 'Loading...' });
            $scope.accountLevel = Purchase.accountLevel;
            $scope.expirationDate = (new Date(Purchase.expirationDate)).toLocaleDateString();

            if (!window.inAppPurchase) {
                $ionicLoading.hide();
                console.log("Fail to load plugin inAppPurchase");
                return;
            }

            if (ionic.Platform.isIOS()) {
                Purchase.productId = 'non1year';
            }
            else if (ionic.Platform.isAndroid()) {
                Purchase.productId = 'annually';
            }

            console.log('productId='+Purchase.productId);

            inAppPurchase
                .getProducts([Purchase.productId])
                .then(function (products) {
                    console.log(JSON.stringify(products));
                    $scope.product = products[0];
                    $ionicLoading.hide();
                })
                .catch(function (err) {
                    $ionicLoading.hide();
                    console.log(err);
                    $ionicPopup.alert({
                        title: 'get products',
                        template: JSON.stringify(err)
                    });
                });
        });
```
### Console output
I/chromium: [INFO:CONSOLE(245)] "Error retrieving SKU details"

### Version of cordova
$ cordova --version
5.4.1
### Version of iOS/Android
6.0.1

**Comment by kimalec** [comment] 2016-04-20 15:24
It works with cordova 6.1.1

**Comment by AlexDisler** [comment] 2016-04-27 02:26
Hi, was the issue resolved for you?

**Comment by fenta23** [comment] 2016-04-28 08:36
Hi Alex,
not sure if it's the same, but i have kind of the same problem.
I'm on Android 6.0.1 (Nexus 5) and the LogCat says that there are 2 products (Native log)
04-28 10:29:15.045  8910  8951 D google.payments: get sku:com.digitalroyal.maimapdev.bundleall
04-28 10:29:15.045  8910  8951 D google.payments: get sku:com.digitalroyal.maimapdev.kapitel1

But my log in .inAppPurchase.getProducts(productIds)...
 console.log('------------products------------')
 console.log(receivedProducts)
 console.log(JSON.stringify(receivedProducts))
 console.log('------------products------------')

says there are no products and no error:

04-28 10:29:15.132  8910  8910 I chromium: [INFO:CONSOLE(72021)] "------------products------------", source: file:///android_asset/www/build/js/app.bundle.js (72021)
04-28 10:29:15.132  8910  8910 I chromium: [INFO:CONSOLE(72022)] "", source: file:///android_asset/www/build/js/app.bundle.js (72022)
04-28 10:29:15.132  8910  8910 I chromium: [INFO:CONSOLE(72023)] "[]", source: file:///android_asset/www/build/js/app.bundle.js (72023)
04-28 10:29:15.132  8910  8910 I chromium: [INFO:CONSOLE(72024)] "------------products------------", source: file:///android_asset/www/build/js/app.bundle.js (72024)


Any ideas? Btw, thanks for the awesome plugin, learned a lot about inapppurchases, but still painfull task;)

**Comment by fenta23** [comment] 2016-04-28 09:42
okay, got an answer http://stackoverflow.com/questions/23914789/android-inventory-getskudetails-returning-null

i released the app in beta test, but try it in alpha test now...

**Comment by fenta23** [comment] 2016-04-28 15:20
okay, forget about my issue, after 2h of waiting i get the products from google! thats crazy...

**Comment by AlexDisler** [comment] 2016-04-29 14:30
Glad you got it working 👍 

@kimalec I'll close this for now but please reopen if you still have an issue and there's a way for me to reproduce it.

**Closed by AlexDisler** 2016-04-29 14:30 UTC

**Comment by richardmarais** [comment] 2017-06-19 14:03
I am getting the same error when `.getProducts(this.PRODUCT_IDS)`:

> Error retrieving SKU details

It was working perfectly, until I added a test user. I tried to make a purchase with the test user.

    this.iap.buy(item.productId).then((data) => {
      return this.iap.consume(data.productType, data.receipt, data.signature);
    }).then(() => {
      console.log('product was successfully consumed!');

But now I cannot access the products any longer.

I have read [here](https://github.com/AlexDisler/cordova-plugin-inapppurchase/issues/55) that the reason may be because testers cannot consume a product and offers this solution:

SOLUTION:
Pull up "orders" on the Play Console and "cancel" the pending purchase.

However, then I have two questions:

1. How do you test purchases, if a tester cannot consume a product?
2. Where do you pull up orders on the Play Console? I do look at "Order Management", but there are no orders listed.

Thanks
